# Generated by Django 5.2.17 on 2026-10-02 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0003_riderequest_driver_driverprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderequest',
            name='cash_paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='riderequest',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash')], default='cash', max_length=10),
        ),
        migrations.AddField(
            model_name='riderequest',
            name='payment_status',
            field=models.CharField(choices=[('due', 'Due'), ('paid', 'Paid')], default='due', max_length=10),
        ),
    ]
